---
title: "3. Write a Function!"
description: |
  Demonstration of how to write a function with personality research data.
author:
  - name: Raleigh Goodwin, Vinita Vader
date: 05-28-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Introduction:

This is a tutorial on using functional programming to solve specific problems in research. This tutorial addresses the issue of Ipsatization which consists of methods of data transformation used in Personality Psychology and Social Psychology research. Ipsatization transforms each participant's ratings relative to their average response such that the total and the average of the participant's scores across all items in the dataset are zero (or another constant for all people) (Greer and Dunlap, 1997) [<https://psycnet.apa.org/record/1997-06270-006>].

Packages such as (`multicon)[https://cran.r-project.org/web/packages/multicon/multicon.pdf]` have built functions like `ipsatize` [<https://rdrr.io/cran/multicon/man/ipsatize.html>] which enable standardizing rows of the dataframes being studied. However it does not address the various types of ipsative scorings available for carrying out different transformations.

An important aspect of using data transformations involves understanding the relationship between raw data and transformed data. The purpose of the function built here will be to address this specific issue.



